version: "3.9"
services:
  web:
    build: .
    ports:
    - "8000:8000"
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/outlays_manager
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: